touch manager_view.h # 定义ManagerView抽象基类
touch manager_view_impl.h # 声明ManagerVieImpl类
touch manager_view_impl.cpp # 实现ManagerViewImpl类
touch manager_ctrl.h # 定义ManagerCtrl抽象基类
touch manager_ctrl_impl.h # 声明ManagerCtrlImpl类
touch manager_ctrl_impl.cpp # 实现ManagerCtrlImpl类
touch manager_mode.h # 定义ManagerMode抽象基类
touch manager_mode_impl.h # 声明ManagerModeImpl类
touch manager_mode_impl.cpp # 实现ManagerModeImpl类
touch manager.h # 声明Manager类
touch manager.cpp # 实现Manager类
touch service_view.h # 定义ServiceView抽象基类
touch service_view_impl.h # 声明ServiceViewImpl类
touch service_view_impl.cpp # 实现ServiceViewImpl类
touch service_ctrl.h # 定义ServiceCtrl抽象基类
touch service_ctrl_impl.h # 声明ServiceCtrlImpl类
touch service_ctrl_impl.cpp # 实现ServiceCtrlImpl类
touch service_mode.h # 定义ServiceMode抽象基类
touch service_mode_impl.h # 声明ServiceModeImpl类
touch service_mode_impl.cpp # 实现ServiceModeImpl类
touch department.h # 声明Department类
touch department.cpp # 实现Department类
touch employee.h # 声明Employee类
touch employee.cpp # 实现Employee类
touch main.cpp # 定义main()函数
touch emis.h # 声明全局变量
touch emis.cpp # 定义全局变量
touch tools.h # 声明工具函数
touch tools.cpp # 定义工具函数
touch Makefile # 项目制作脚本
